# Generated by Django 4.0.3 on 2022-03-16 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='OtherWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('inner_phone', models.CharField(max_length=200, null=True)),
                ('outer_phone', models.CharField(max_length=200, null=True)),
                ('mobile_phone', models.CharField(max_length=200, null=True)),
                ('post', models.CharField(max_length=255, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('birth_date', models.CharField(max_length=200, null=True)),
                ('account_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Дополнительный отрудник',
                'verbose_name_plural': 'Дополнительные сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('inner_phone', models.CharField(max_length=200, null=True)),
                ('outer_phone', models.CharField(max_length=200, null=True)),
                ('mobile_phone', models.CharField(max_length=200, null=True)),
                ('post', models.CharField(max_length=255, null=True)),
                ('room', models.CharField(max_length=50, null=True)),
                ('birth_date', models.CharField(max_length=200, null=True)),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darktheme', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
