# Generated by Django 4.0.3 on 2022-03-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherworker',
            name='gender',
            field=models.CharField(choices=[('1', 'None'), ('2', 'Male'), ('3', 'Female')], default=1, max_length=1),
        ),
    ]
