# Generated by Django 4.1 on 2022-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.BooleanField(default=True),
        ),
    ]
