# Generated by Django 4.1 on 2022-09-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0005_remove_post_active_post_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherworker',
            options={'verbose_name': 'Дополнительный cотрудник', 'verbose_name_plural': 'Дополнительные сотрудники'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='editor',
        ),
    ]
